Done 20-22 inc
Xrefullx/golang-shorturl pull request #9
Opened 2023-04-02 10:23 UTC by Xrefullx

2023-04-05 09:31 UTC, rktkov requested changes

2023-04-05 09:31 UTC, rktkov commented on internal/storage/psql/storage.go
> +	st.waitAsyncEnd = true
Я не увидел место в коде, где флагу присваивается значение false. Т.е. флаг всегда true - тогда не совсем понятно зачем он нужен, если он сигнализирует только об одном состоянии. А в таком случае и метод интерфейса, возвращающий значения флага не нужен, потому что мы в любом случае должны будет ждать завершения тасок репозитория. Если все так, то лучше весь этот код удалить. И нам достаточно следить за состоянием канала storageAsyncEnded, чтобы корректно завершить работу.

2023-04-07 07:00 UTC, rktkov approved these changes

2023-04-07 07:00 UTC, rktkov commented on internal/storage/psql/storage.go
> +	waitAsyncEnd      bool
Все так же флаг не несет никакого смысла, может его удалить, а если метод интерфейса нужен, потому что он активно используется в другой реализации интерфейса, то может там стоит возвращать true,  и не плодить лишние поля в структуре.

2023-04-07 09:02 UTC, Xrefullx commented
merge 20-22

2023-04-07 09:03 UTC, merged